### PR TITLE
fix: Add error messages for missing annotations

### LINKED ISSUE #205: `vcf-report` exits with "thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value'" error
I'm testing out `vcf-report` with VCF files generated by VarDict, as I was looking for packages/libraries/tools to generate oncoprint plots for our workflow: https://github.com/Clinical-Genomics/BALSAMIC

I followed routine install on MacOS Big Sur: `conda create --name rust-bio-tools rust-bio-tools`

And ran the following command:
```
rbt vcf-report fasta.fa --vcfs a=sample1.vcf.gz b=sample2.vcf.gz --bams a:sampleA=sample1.bam b:sampleB=sample2.bam -- oncoprint_example/
```

The output is quite cryptic and doesn't really tell me what went wrong:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/bcf/report/table_report/create_report_table.rs:65:thread '77<unnamed>
' panicked at 'called `Option::unwrap()` on a `None` valuenote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
', src/bcf/report/table_report/create_report_table.rs:65:77
```

Are there any example files or documentations I can follow to find out what might be wrong?

### PR DESCRIPTION
**Pull request by fxwiegand**
Just a quick PR that fixes #205.

### CODE REVIEW

File: src/bcf/report/oncoprint.rs [hunk 1]
```diff
@@ -63,9 +63,9 @@ pub fn oncoprint(
     for (sample, path) in sample_calls.iter().sorted() {
         let bcf_reader = bcf::Reader::from_path(path)?;
         let header_records = bcf_reader.header().header_records();
-        let ann_fields: Vec<_> = get_ann_description(header_records).unwrap_or_else(|| {
-            panic!("No ANN field found. Please only use VEP-annotated VCF-files.")
-        });
+        let ann_fields: Vec<_> = get_ann_description(header_records)
+            .context("No annotations found. Please only use VEP-annotated VCF-files.")
+            .unwrap();
```
Comment (johanneskoester) [inline src/bcf/report/oncoprint.rs:68]: Would be better to not unwrap here and below. Rather return the error.

**Review by johanneskoester — CHANGES_REQUESTED** [review]

File: src/bcf/report/oncoprint.rs (hunk 1 above)
Comment (fxwiegand) [reply src/bcf/report/oncoprint.rs]: Changed the return type of `get_ann_description()` to `Result<T>`.

**Review by johanneskoester — APPROVED** [review]
